from datetime import datetime
import os

from dotenv import load_dotenv

# Load variables from a local .env file if present (no-op in production
# where env vars are set directly by the platform).
load_dotenv()

# Premier League Gameweek Schedule
# Format: (gameweek_number, start_date, deadline, end_time)  — naive UK wall-clock times.
# Generated from the Fantasy Premier League API; run `python -m scripts.gen_schedule`
# to (re)build this list, then hand-edit any row as needed.
GAMEWEEK_SCHEDULE = [
    # Generated by scripts/gen_schedule.py on 2026-10-08 (end_time = last kickoff + 3h).
    # Re-running the script overwrites this list; edit by hand freely in between.
    (1, datetime(2026, 8, 21), datetime(2026, 8, 21, 18, 30), datetime(2026, 8, 24, 23, 0)),
    (2, datetime(2026, 8, 28), datetime(2026, 8, 28, 18, 30), datetime(2026, 8, 31, 23, 0)),
    (3, datetime(2026, 9, 4), datetime(2026, 9, 4, 18, 30), datetime(2026, 9, 6, 19, 30)),
    (4, datetime(2026, 9, 12), datetime(2026, 9, 12, 13, 30), datetime(2026, 9, 14, 23, 0)),
    (5, datetime(2026, 9, 18), datetime(2026, 9, 18, 18, 30), datetime(2026, 9, 20, 19, 30)),
    (6, datetime(2026, 10, 10), datetime(2026, 10, 10, 11, 0), datetime(2026, 10, 12, 23, 0)),
    (7, datetime(2026, 10, 17), datetime(2026, 10, 17, 11, 0), datetime(2026, 10, 19, 23, 0)),
    (8, datetime(2026, 10, 23), datetime(2026, 10, 23, 18, 30), datetime(2026, 10, 25, 19, 30)),
    (9, datetime(2026, 10, 31), datetime(2026, 10, 31, 11, 0), datetime(2026, 11, 2, 23, 0)),
    (10, datetime(2026, 11, 6), datetime(2026, 11, 6, 18, 30), datetime(2026, 11, 8, 19, 30)),
    (11, datetime(2026, 11, 21), datetime(2026, 11, 21, 11, 0), datetime(2026, 11, 23, 23, 0)),
    (12, datetime(2026, 11, 27), datetime(2026, 11, 27, 18, 30), datetime(2026, 11, 29, 19, 30)),
    (13, datetime(2026, 12, 2), datetime(2026, 12, 2, 18, 30), datetime(2026, 12, 2, 23, 0)),
    (14, datetime(2026, 12, 5), datetime(2026, 12, 5, 13, 30), datetime(2026, 12, 5, 18, 0)),
    (15, datetime(2026, 12, 12), datetime(2026, 12, 12, 13, 30), datetime(2026, 12, 12, 18, 0)),
    (16, datetime(2026, 12, 19), datetime(2026, 12, 19, 13, 30), datetime(2026, 12, 19, 18, 0)),
    (17, datetime(2026, 12, 26), datetime(2026, 12, 26, 11, 0), datetime(2026, 12, 27, 22, 0)),
    (18, datetime(2026, 12, 29), datetime(2026, 12, 29, 18, 0), datetime(2026, 12, 30, 23, 15)),
    (19, datetime(2027, 1, 1), datetime(2027, 1, 1, 18, 30), datetime(2027, 1, 3, 19, 30)),
    (20, datetime(2027, 1, 5), datetime(2027, 1, 5, 18, 0), datetime(2027, 1, 7, 23, 0)),
    (21, datetime(2027, 1, 16), datetime(2027, 1, 16, 13, 30), datetime(2027, 1, 16, 18, 0)),
    (22, datetime(2027, 1, 23), datetime(2027, 1, 23, 13, 30), datetime(2027, 1, 23, 18, 0)),
    (23, datetime(2027, 1, 30), datetime(2027, 1, 30, 13, 30), datetime(2027, 1, 30, 18, 0)),
    (24, datetime(2027, 2, 6), datetime(2027, 2, 6, 13, 30), datetime(2027, 2, 6, 18, 0)),
    (25, datetime(2027, 2, 10), datetime(2027, 2, 10, 18, 30), datetime(2027, 2, 10, 23, 0)),
    (26, datetime(2027, 2, 20), datetime(2027, 2, 20, 13, 30), datetime(2027, 2, 20, 18, 0)),
    (27, datetime(2027, 2, 27), datetime(2027, 2, 27, 13, 30), datetime(2027, 2, 27, 18, 0)),
    (28, datetime(2027, 3, 3), datetime(2027, 3, 3, 18, 30), datetime(2027, 3, 3, 23, 0)),
    (29, datetime(2027, 3, 13), datetime(2027, 3, 13, 13, 30), datetime(2027, 3, 13, 18, 0)),
    (30, datetime(2027, 3, 20), datetime(2027, 3, 20, 13, 30), datetime(2027, 3, 20, 18, 0)),
    (31, datetime(2027, 4, 10), datetime(2027, 4, 10, 13, 30), datetime(2027, 4, 10, 18, 0)),
    (32, datetime(2027, 4, 17), datetime(2027, 4, 17, 13, 30), datetime(2027, 4, 17, 18, 0)),
    (33, datetime(2027, 4, 24), datetime(2027, 4, 24, 13, 30), datetime(2027, 4, 24, 18, 0)),
    (34, datetime(2027, 5, 1), datetime(2027, 5, 1, 13, 30), datetime(2027, 5, 1, 18, 0)),
    (35, datetime(2027, 5, 8), datetime(2027, 5, 8, 13, 30), datetime(2027, 5, 8, 18, 0)),
    (36, datetime(2027, 5, 15), datetime(2027, 5, 15, 13, 30), datetime(2027, 5, 15, 18, 0)),
    (37, datetime(2027, 5, 23), datetime(2027, 5, 23, 13, 30), datetime(2027, 5, 23, 18, 0)),
    (38, datetime(2027, 5, 30), datetime(2027, 5, 30, 14, 30), datetime(2027, 5, 30, 19, 0)),
]

# User mapping
USER_MAP = {
    "+447387303123": "Aaron",
    # "+16043175991": "Adam",
    "+64272806500": "Aubrey",
    "+31618271215": "Ben",
    "+447950139194": "Calum",
    "+447845948768": "David",
    "+64211206201": "Dom",
    "+447871617112": "Fraser",
    "+447587626672": "Jerome",
    "+6421581535": "John",
    "+447517587086": "Joss",
    "+447375356774": "Peter",
    # "+447526186549": "Rohan",
    "+447438895095": "Sam",
    "+447506811604": "Cal",
    "+447881112921": "Olivia",
    "+64273904019": "Reuben",
}

# Google Sheets setup
SPREADSHEET_ID = os.environ.get('GOOGLE_SHEET_ID', 'your-google-sheet-id')
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']

ADMIN_PHONE = os.environ.get('ADMIN_PHONE', "+447375356774")

# Twilio setup
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN')
TWILIO_FROM_NUMBER = os.environ.get('TWILIO_WHATSAPP_NUMBER', 'whatsapp:+14155238886')
