#!/usr/bin/env python3
"""Generate GAMEWEEK_SCHEDULE in config/settings.py from the free Fantasy
Premier League API — so you never have to type the schedule out by hand.

Each schedule row is ``(gameweek, start_date, deadline, end_time)`` where:
  * start_date  = date of the gameweek's first kickoff  (midnight, UK time)
  * deadline    = FPL's own deadline_time               (UK wall-clock time)
  * end_time    = the gameweek's last kickoff + a buffer (UK wall-clock time)

All datetimes are written as NAIVE UK wall-clock values, because the rest of
the app calls ``uk_tz.localize()`` on them (see utils/date_utils.py). The list
is always emitted contiguously from GW1, which the app relies on for its
positional ``GAMEWEEK_SCHEDULE[gw-2]`` lookups.

Usage:
    python -m scripts.gen_schedule            # rewrite config/settings.py
    python -m scripts.gen_schedule --dry-run  # print the block, write nothing
    python -m scripts.gen_schedule --buffer-hours 6

Re-running OVERWRITES the list, including any manual edits. That's the intended
workflow: generate when the season's fixtures change, then hand-tweak as you
like until the next regeneration.
"""

import argparse
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

import requests

FPL_BASE = "https://fantasy.premierleague.com/api"
UK_TZ = ZoneInfo("Europe/London")
SETTINGS_PATH = Path(__file__).resolve().parent.parent / "config" / "settings.py"

# Matches the whole ``GAMEWEEK_SCHEDULE = [ ... ]`` literal, including the
# closing bracket on its own line.
SCHEDULE_RE = re.compile(r"GAMEWEEK_SCHEDULE = \[.*?\n\]", re.DOTALL)


def _get_json(url):
    resp = requests.get(url, timeout=20, headers={"User-Agent": "gen_schedule/1.0"})
    resp.raise_for_status()
    return resp.json()


def _to_uk_naive(iso_utc):
    """'2026-08-21T17:30:00Z' -> naive UK wall-clock datetime (18:30 in BST)."""
    dt = datetime.fromisoformat(iso_utc.replace("Z", "+00:00"))
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(UK_TZ).replace(tzinfo=None)


def build_rows(buffer_hours):
    """Return a sorted list of (gw, start_date, deadline, end_time) tuples."""
    events = _get_json(f"{FPL_BASE}/bootstrap-static/")["events"]
    fixtures = _get_json(f"{FPL_BASE}/fixtures/")

    # Group confirmed kickoff times (UK-naive) by gameweek.
    kickoffs = {}
    for f in fixtures:
        gw, ko = f.get("event"), f.get("kickoff_time")
        if gw and ko:
            kickoffs.setdefault(gw, []).append(_to_uk_naive(ko))

    rows = []
    for e in sorted(events, key=lambda e: e["id"]):
        gw = e["id"]
        deadline = _to_uk_naive(e["deadline_time"])
        kos = sorted(kickoffs.get(gw, []))
        if kos:
            first, last = kos[0], kos[-1]
            start_date = datetime(first.year, first.month, first.day)
            end_time = last + timedelta(hours=buffer_hours)
        else:
            # No confirmed kickoffs yet (fixtures TBC) — fall back to the
            # deadline so the row is still usable and clearly a placeholder.
            print(f"  ! GW{gw}: no kickoff times yet, using deadline as fallback")
            start_date = datetime(deadline.year, deadline.month, deadline.day)
            end_time = deadline + timedelta(days=3)
        rows.append((gw, start_date, deadline, end_time))
    return rows


def _fmt_dt(dt, date_only=False):
    if date_only:
        return f"datetime({dt.year}, {dt.month}, {dt.day})"
    return f"datetime({dt.year}, {dt.month}, {dt.day}, {dt.hour}, {dt.minute})"


def render_block(rows, buffer_hours):
    generated = datetime.now(UK_TZ).strftime("%Y-%m-%d")
    lines = [
        "GAMEWEEK_SCHEDULE = [",
        f"    # Generated by scripts/gen_schedule.py on {generated} "
        f"(end_time = last kickoff + {buffer_hours}h).",
        "    # Re-running the script overwrites this list; edit by hand freely in between.",
    ]
    for gw, start_date, deadline, end_time in rows:
        lines.append(
            f"    ({gw}, {_fmt_dt(start_date, date_only=True)}, "
            f"{_fmt_dt(deadline)}, {_fmt_dt(end_time)}),"
        )
    lines.append("]")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="print the generated block without writing the file")
    parser.add_argument("--buffer-hours", type=int, default=3,
                        help="hours after the last kickoff to set end_time (default: 3)")
    args = parser.parse_args()

    print("Fetching schedule from the FPL API...")
    rows = build_rows(args.buffer_hours)
    block = render_block(rows, args.buffer_hours)
    print(f"Built {len(rows)} gameweeks (GW{rows[0][0]}–GW{rows[-1][0]}).")

    if args.dry_run:
        print("\n--- dry run, not writing ---\n")
        print(block)
        return

    source = SETTINGS_PATH.read_text()
    if not SCHEDULE_RE.search(source):
        sys.exit(f"Could not find a GAMEWEEK_SCHEDULE list in {SETTINGS_PATH}")
    new_source = SCHEDULE_RE.sub(lambda _: block, source, count=1)
    SETTINGS_PATH.write_text(new_source)
    print(f"Wrote GAMEWEEK_SCHEDULE to {SETTINGS_PATH}")


if __name__ == "__main__":
    main()
